### ISSUE TITLE
Can't use other ports

### ISSUE THREAD

**Issue by sebastienvermeille** [Enalean/docker-tuleap-aio#10]
Hello I tried to install this docker image but when I map my public ports it works badly :

-p 8088:80 \
-p 4443:443 \
-p 2222:22 \

When I visit the page it works but when I try to login it goes again to my.ip.address/account/login.php not my.ip.address:4443/account/login.php

Could you add support for it that would be great :)

**Comment by vaceletm** [comment]
If you want to run on other ports, you should edit manually /etc/tuleap/conf/local.inc on the container (or to edit from the volume, the configuration is saved as the data) to match your changes. Tuleap should be aware of it's public facing name/ports to run properly)

**Comment by LeSuisse** [comment]
I close this issue as an answer have been provided.

**Comment by maurocolella** [comment]
I understand that Tuleap wants a dedicated server rather than just a containerized environment, but I'd like to point out that without port mapping, it's extremely difficult to use Tuleap with docker at all.

I run a small home server with multiple applications. I was looking for a solution to track personal projects. If I start the docker container with 443 unmapped, 22 unmapped, and a mapping such as 9007:80, or anything really, the app enters some unaccounted for state where I cannot access configuration files (files don't seem to be written), and port <whatever> is marked as unresponsive (by my management software).

I cannot take this and recommend it. 

Further: I can think of scenarios when containerized deployments of parallel instances might make sense, for example, if a company wishes to offer managed Tuleap hosting, and seeks to render deployment straightforward based on a containerized solution.

(Ok, that case might not be ideal architecturally, but there *have* to be situations when containers make sense for Tuleap, even if tightly integrated with the system).

Anyway. I just wanted to point out that the docker "testbed" is effectively not very friendly on any hardware that isn't dedicated, and that potentially has other apps already hosted.

**Comment by vaceletm** [comment]
As answer to the initial question, tuleap does run different ports without any trouble. It's just not automated and you have to work a bit to update the configuration files to tell the app where it's running.

In understand it can be frustrating to have to do things manually but we do welcome contributions to make this automated.
