### ISSUE TITLE
Does not login docker with user "root "

### ISSUE THREAD

**Issue by carl19781107** [Enalean/docker-tuleap-aio#26]
Dear all

I deployed a docker  to use  githup "https://github.com/Enalean/docker-tuleap-aio" , it has startup now.
But i don‘t logoin with user "root " ,the detial information as belw，pls help me check it.

root@ALMTuleap:/root# docker ps
CONTAINER ID    IMAGE        COMMAND         CREATED       STATUS         PORTS           NAMES
aa4a90468402        enalean/tuleap-aio   "/root/app/run.sh"   33 minutes ago      Up 33 minutes       22/tcp, 443/tcp, 0.0.0.0:80->80/tcp   elated_shaw

root@ALMTuleap:/root# docker exec -ti aa4a90468402  cat /data/root/.tuleap_passwd
Mysql user (root) : \<removed\>
Codendiadm unix & DB (codendiadm):  \<removed\>
Libnss-mysql DB user (dbauthuser):  \<removed\>
Site admin password (admin):  \<removed\>
root:  \<removed\>

root@ALMTuleap:/root# docker login aa4a90468402
Username: root
Password: 
Error response from daemon: Get https://aa4a90468402/v1/users/: dial tcp: lookup aa4a90468402: no such host

**Comment by nterray** [comment]
You should run `docker exec -ti ... bash`.

Does it answer your question?

**Comment by LeSuisse** [comment]
I have edited you original message to remove all the passwords. If you are running this container outside a controlled test environment I strongly suggest to either:
 * change all these passwords immediately
 * trash the data volume and start over, new passwords will be generated

To log in on the web interface as a site administrator the first time you should use the credentials given on the line *Site admin password* in the `.tuleap_passwd` file.

You seem confused by the Docker commands, `docker login` does do at all what you think it does. I suggest you take a look at the [Get started of the Docker documentation](https://docs.docker.com/get-started/part2/) before trying to use the tuleap-aio image.

Since your issue is not related to the tuleap-aio image, I close this issue.

**Comment by carl19781107** [comment]
Logon successfully. Thank you  nterray

**Comment by carl19781107** [comment]
Thank you   LeSuisse .
