### ISSUE TITLE
VIRTUAL_HOST redirection not working via environment Variables

### ISSUE THREAD

**Issue by mtenrero** [Enalean/docker-tuleap-aio#28]
Running container with the following parameters always redirects to localhost HTTPS port (443)

docker run -ti -e VIRTUAL_HOST=host.domain.com -p 8080:80 -p 8443:443 -v [...]

So I think the VIRTUAL_HOST variable is not working properly.

**Comment by LeSuisse** [comment]
Hi,

Did you set the VIRTUAL_HOST environment variable on the first run? If no, that's why it still redirects you to localhost.

That's said the initial setup does not expect not standard ports to be used so even if you set properly the VIRTUAL_HOST variable on the first run you are going to need to edit the `/etc/tuleap/conf/local.inc` file by hand to match your need.

**Comment by mtenrero** [comment]
Hi, editing manually `/etc/tuleap/conf/local.inc` solved the problem. The problems came using non standard ports as you say.

Thanks for your help. I'll close the issue.

**Comment by rgstephens** [comment]
I just found this post.  @LeSuisse I think the comments above about the importance of VIRTUAL_HOST on first run and how to set an alternate port should be added to the README.md.

Thanks again for this app.
