### ISSUE TITLE
Tuleap behind Traefik

### ISSUE THREAD

**Issue by yacinelazaar** [Enalean/docker-tuleap-aio#74]
Hi, 
I'm quite curious if anyone tried runnig tuleap behind a reverse proxy like traefik and figured it out.
Here is my compose file:
`version: '3.5'

services:

# ---------------------------- Traefik ---------------------------- #
  traefik:
    image: traefik
    restart: always
    command: --api --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    labels:
      - traefik.frontend.rule=Host:traefik.${DOMAIN}
      - traefik.port=8008
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - ./traefik.toml:/traefik.toml
      - ./certs:/certs
      - traefik-tmp-data:/tmp
    container_name: traefik

# ---------------------------- Tuleap ---------------------------- #
  tuleap:
    image: enalean/tuleap-aio
    restart: always
    networks:
      - web
    environment:
      - VIRTUAL_HOST=tuleap.${DOMAIN}
      - DB_HOST=tuleap-mysql
      - MYSQL_ROOT_PASSWORD=${TULEAP_MYSQL_ROOT_PASSWORD}
    labels:
      - traefik.frontend.rule=Host:tuleap.${DOMAIN}
      - traefik.port=80
    volumes:
      - tuleap-data:/data
    depends_on:
      - tuleap-mysql
    container_name: tuleap

  tuleap-mysql:
    image: mysql:5.6
    restart: always
    networks:
      - web
    environment:
      - MYSQL_ROOT_PASSWORD=${TULEAP_MYSQL_ROOT_PASSWORD}
    volumes:
      - tuleap-mysql-data:/var/lib/mysql
      - ./tuleap/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    container_name: tuleap-mysql

# ------------------- Container Volumes + Network ----------------- #
volumes:
  traefik-tmp-data:
  tuleap-data:
  tuleap-mysql-data:
`

My Tuleap container fails to start and keeps throwing this error repetitively:
` exited: postfix (exit status 0; expected)
2019-06-19 02:05:20,671 INFO received SIGCLD indicating a child quit
2019-06-19 02:05:23,171 CRIT reaped unknown pid 1416)
2019-06-19 02:05:23,171 INFO received SIGCLD indicating a child quit
` 

I fail to see how is that related to postfix.

**Comment by LeSuisse** [comment]
Hi,

The sample configuration given here https://docs.tuleap.org/administration-guide/system-administration/advanced-deployments.html#deploy-tuleap-behind-a-reverse-proxy is for nginx but the requirements should mostly be the same whatever the reverse proxy you decide to use.

You need to pass/set the headers X-Real-IP, X-Forwarded-Proto, X-Forwarded-For, Host and Destination.

Also note the Tuleap container expects to be reached via HTTPS on 443/TCP.

**Comment by yassinelazaar** [comment]
> Also note the Tuleap container expects to be reached via HTTPS on 443/TCP.
But the reverse proxy occupies that port on the host. Can I publish to different one?

**Comment by LeSuisse** [comment]
It's the port used by the container, the ports bound on the host does not matter.

**Comment by yassinelazaar** [comment]
This is a damn headache to configure with traefik. Is there any way to disable ssl?

**Comment by dduportal** [comment]
The issue here (with Traefik but as well as any other reverse proxy), is that the docker image tuleap/aio is opinionated to provide a good user experience, without anything else.
Unless there is a way to disable the SSL termination at the "internal nginx" level, there is no way to terminate SSL outside (or it would be a Man on the middle :) ).

@LeSuisse is there a way to disable SSL or to directly access the php server in pure http?

**Comment by LeSuisse** [comment]
At the moment no, it's not possible with this image. You might be able to extends it to suit your needs though. That would require to customize `/etc/nginx/conf.d/tuleap.conf` and change the value of `sys_trusted_proxies` in `/etc/tuleap/conf/local.inc`.

That's said I took a quick look at the Traefik documentation and I think it might be manageable as is.
It looks like telling to Traefik that the backend uses HTTPS can be done by adding the label `traefik.protocol=https`. The annoying part is that by default the Tuleap image will generate a self signed certificate so Traefik will (rightfully) refuse to communicate with it because the certificate is not signed by a trusted certificate authority. Adding the self signed certificate to the list of trusted CA in the Traefik container is annoying and might be overkill for the level of security you need (if really want to go there you should probably consider using something like HashiCorp Vault to manage the internal CA but that would also require to at least customize the Tuleap image). The other way to approach it is to tell to Traefik to skip the TLS verification. Unfortunately that does not seem possible to do that on per backend basis (there are some discussions around this in containous/traefik#3038). If it's acceptable to you to skip the TLS verification for all your backends, the global option `insecureSkipVerify` can be used.

**Comment by dduportal** [comment]
Thanks @LeSuisse 👍 
It works with these labels (and insecureSkipVerify enable globally):

```yml
    labels:
      - traefik.frontend.rule=Host:app.domain.com
      - traefik.port=443
      - traefik.frontend.passHostHeader=true
      - traefik.protocol=https
```

**Comment by LeSuisse** [comment]
Thanks for the confirmation!

I will also check on my end just to confirm everything looks is running as expected on the Tuleap side and a note in the README.

**Comment by dduportal** [comment]
Cool ! To be transparent, I totally forgot to mention the `traefik.protocol` label to @yassinelazaar when he asked for help in Traefik's support channel, so it's a great help!

I'm thinking about the certificate generation: if the certificate authority is provided, could it be mounted and used in tuleap container for the certificate generation?

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
