### ISSUE TITLE
How can i use docker-image without https?

### ISSUE THREAD

**Issue by misterx** [Enalean/docker-tuleap-aio#78]
I have a front nginx proxy with https certificates. I want to proxy from front:https request to tuleap:http,  but I receive many redirects.

**Comment by LeSuisse** [comment]
Hi,

Your issue is probably the same than the one described in #65.

**Comment by rolandoisidoro** [comment]
@misterx , I'm trying to deal with a similar situation, but I have an Apache server in front dealing with the SSL certificates. Have you checked out Tuleap's documentation on [Advanced deployments | Deploy Tuleap behind a reverse proxy](https://docs.tuleap.org/administration-guide/system-administration/advanced-deployments.html) ?

I tracked the origin of the "too many redirects" error to [Tuleap's Nginx server block](https://github.com/Enalean/tuleap/blob/master/src/etc/nginx/tuleap.conf.dist#L43). On line 43 there's a 301 redirect from port 80 to 443, which means that it'll always try to load the app via HTTPS.

From my experience, you have to tweak Tuleap's Nginx server block as follow to prevent the redirect and keep everything working over HTTP:

- Comment line 43;
- Copy lines 28 to 31 from the port 443 block onto the port 80 block.

Additionally you'll also have to edit Tuleap's `local.inc` and set the value of [`$sys_https_host`]((https://github.com/Enalean/tuleap/blob/master/src/etc/local.inc.dist#L77)) to an empty string.

The last step should be to add the IP of your Nginx proxy to `$sys_trusted_proxies` on the same file, but I'm experiencing some problems. The [function to see if the request is coming from a trusted proxy](https://github.com/Enalean/tuleap/blob/master/src/common/include/HTTPRequest.class.php#L191) checks the `REMOTE_ADDR` header value against the values we set on `$sys_trusted_proxies`, at this point **I'm getting the container IP instead of the reverse proxy** on that header. I'm still looking at why this is happening, but since the container itself has its own Nginx reverse proxy in front of an Apache web server, it's taking me longer to get to the bottom of the problem.

**Comment by rolandoisidoro** [comment]
@misterx , I've just setup a quick Tuleap install using a Docker container and set [traefik](url) as a reverse proxy in front of it. Checked the `REMOTE_ADDR` and got traefik's container IP, which was the expected value and rules out any problem in the Tuleap container.

PS:. Got back to the other environment where the IP was wrong an it turned out to be a parameter regarding load balancing on our K8s setup.

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
